version: 1.0
provider:
  name: openfaas
  gateway: http://openfaas.k3s.homelab  # remplacer par l'IP du LoadBalancer K3s

functions:
  generate-password:
    lang: python3-http
    handler: ./functions/generate-password
    image: ghcr.io/alexandreschoukroun/generate-password:latest
    imagePullPolicy: Always
    secrets:
      - db-credentials
      - encryption-key

  generate-2fa:
    lang: python3-http
    handler: ./functions/generate-2fa
    image: ghcr.io/alexandreschoukroun/generate-2fa:latest
    imagePullPolicy: Always
    secrets:
      - db-credentials
      - encryption-key

  authenticate:
    lang: python3-http
    handler: ./functions/authenticate
    image: ghcr.io/alexandreschoukroun/authenticate:latest
    imagePullPolicy: Always
    secrets:
      - db-credentials
      - encryption-key
