apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: cofrap
data:
  config.js: |
    window.COFRAP_CONFIG = {
      OPENFAAS_URL: "http://openfaas.k3s.homelab/function"
    };
