name: CI — generate-password

# Se déclenche à chaque push ou PR sur ces branches
on:
  push:
    branches:
      - main
      - feat/generate-password
  pull_request:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code du repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installe Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Installe les dépendances de la fonction
      - name: Install dependencies
        run: pip install -r functions/generate-password/requirements.txt

      # 4. Lance le test local (mock BDD — pas besoin de PostgreSQL)
      - name: Run tests
        run: python functions/generate-password/test_local.py
